services:

  mysql:
    image: mysql:8.0
    volumes:
      - math-calc-mysql-data:/var/lib/mysql
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: math-calcs

volumes:
  math-calc-mysql-data:
