services:

  mysql:
    image: mysql:8.0
    volumes:
      - square_mertic-mysql-data:/var/lib/mysql
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: square_mertics

volumes:
  square_mertic-mysql-data:
