services:

  mysql:
    image: mysql:8.0
    volumes:
      - MathCalc-mysql-data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: MathCalc

volumes:
  MathCalc-mysql-data:
