services:

  cube:
   build: ./cube/
   ports: 
     - "5001:5001"

  mysql:
    image: mysql:8.0
    volumes:
      - ./MathCalc-mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: MathCalc

volumes:
  MathCalc-mysql-data:
